In [1]:
import pandas as pd
pd.options.mode.chained_assignment = None  # default='warn'
import numpy as np

In [2]:
# Story definition
from common_variables import *


# All functions for text analysis are in this script, load when code is run
%load_ext autoreload
%autoreload 1
%aimport common_functions

from common_text_analysis import *

In [3]:
# Save to use in next analysis
results = pd.read_csv(f'{path_data_files}/data_final/cleaned_combined_data.csv', index_col=0)
results.head()

,layer_n,rep,story1,story2,story3,story_merged,condition
0,1,1,"Through history, most people didn't die of can...","Through history, most people didn't die of can...","Through history, most people didn't die of can...",People didn't use to die of heart disease and ...,Network
1,1,1,"Through history, most people didn't die of can...","Through history, most people didn't die of can...","Through history, most people didn't die of can...",People didn't use to die or heart disease or c...,Network
2,1,1,"Through history, most people didn't die of can...","Through history, most people didn't die of can...","Through history, most people didn't die of can...",Alexander Fleming discovered penicillin in 192...,Network
3,2,1,People didn't use to die of heart disease and ...,People didn't use to die or heart disease or c...,Alexander Fleming discovered penicillin in 192...,Before the discovery of lifesaving antibiotics...,Network
4,2,1,People didn't use to die of heart disease and ...,People didn't use to die or heart disease or c...,Alexander Fleming discovered penicillin in 192...,People didn't used to die of cancer or heart d...,Network

# Create similarity

## With the original story

In [4]:
# Create jaccard similarity with the original story
results_jac = create_similarity(results.copy(),stop_words=eng_stopwords, fun_similarity=jaccard)
results_jac.to_csv(f'{path_data_files}/data_processing/analysis_similarity_jaccard.csv')

In [5]:
# Read global_emb from the embeddings
results_jac.to_csv(f'{path_data_files}/data_processing/analysis_similarity_jaccard.csv')
results_jac[["layer_n","rep","condition","sim_original_story"]].head()

   layer_n rep condition  sim_original_story
0        1   1   Network            0.138211
1        1   1   Network            0.131222
2        1   1   Network            0.070485
3        2   1   Network            0.025974
4        2   1   Network            0.093023

In [6]:
# Test transformer
sentences = ["go virus","bacteria kills"]
transformer_similarity(*sentences, model_t)

0.29197198152542114

In [7]:
results_trans = create_similarity(results,w2t,create_set=False,stop_words=None,tokenize=False)

In [8]:
# Save to use in next analysis
results_trans.to_csv(f'{path_data_files}/data_processing/analysis_similarity_transformers.csv')
results_trans[["layer_n","rep","condition","sim_original_story"]].head()

   layer_n rep condition  sim_original_story
0        1   1   Network            0.782817
1        1   1   Network            0.783907
2        1   1   Network            0.650665
3        2   1   Network            0.769188
4        2   1   Network            0.665215

In [9]:
results_trans

,layer_n,rep,story1,story2,story3,story_merged,condition,story_original,sim_1,sim_2,sim_3,sim_previous_layer,sim_original_story,sim_os_1,sim_os_2,sim_os_3,sim_wl_12,sim_wl_13,sim_wl_23,sim_within_layer
0,1,1,"Through history, most people didn't die of can...","Through history, most people didn't die of can...","Through history, most people didn't die of can...",People didn't use to die of heart disease and ...,Network,"Through history, most people didn't die of can...",0.782817,0.782817,0.782817,0.782817,0.782817,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
1,1,1,"Through history, most people didn't die of can...","Through history, most people didn't die of can...","Through history, most people didn't die of can...",People didn't use to die or heart disease or c...,Network,"Through history, most people didn't die of can...",0.783907,0.783907,0.783907,0.783907,0.783907,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
2,1,1,"Through history, most people didn't die of can...","Through history, most people didn't die of can...","Through history, most people didn't die of can...",Alexander Fleming discovered penicillin in 192...,Network,"Through history, most people didn't die of can...",0.650665,0.650665,0.650665,0.650665,0.650665,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
3,2,1,People didn't use to die of heart disease and ...,People didn't use to die or heart disease or c...,Alexander Fleming discovered penicillin in 192...,Before the discovery of lifesaving antibiotics...,Network,"Through history, most people didn't die of can...",0.627782,0.641062,0.681327,0.681327,0.769188,0.782817,0.783907,0.650665,0.836250,0.502705,0.644985,0.661313
4,2,1,People didn't use to die of heart disease and ...,People didn't use to die or heart disease or c...,Alexander Fleming discovered penicillin in 192...,People didn't used to die of cancer or heart d...,Network,"Through history, most people didn't die of can...",0.740614,0.854785,0.550680,0.854785,0.665215,0.782817,0.783907,0.650665,0.836250,0.502705,0.644985,0.661313
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
859,2,8-2,"Before the creation of antibiotics in 1929, pe...","Before the creation of antibiotics in 1929, pe...","Before the creation of antibiotics in 1929, pe...","Before the creation of antibiotics, people did...",Chain,"Through history, most people didn't die of can...",0.909532,0.909532,0.909532,0.909532,0.724945,0.795948,0.795948,0.795948,1.000000,1.000000,1.000000,1.000000
860,3,8-2,"Before the creation of antibiotics, people did...","Before the creation of antibiotics, people did...","Before the creation of antibiotics, people did...","In the old days, people did not live long enou...",Chain,"Through history, most people didn't die of can...",0.860390,0.860390,0.860390,0.860390,0.760130,0.724945,0.724945,0.724945,1.000001,1.000001,1.000001,1.000001
861,4,8-2,"In the old days, people did not live long enou...","In the old days, people did not live long enou...","In the old days, people did not live long enou...",In the past people didn't live long enough to ...,Chain,"Through history, most people didn't die of can...",0.848318,0.848318,0.848318,0.848318,0.676952,0.760130,0.760130,0.760130,1.000000,1.000000,1.000000,1.000000
862,5,8-2,In the past people didn't live long enough to ...,In the past people didn't live long enough to ...,In the past people didn't live long enough to ...,People used to live shorter lives because they...,Chain,"Through history, most people didn't die of can...",0.690887,0.690887,0.690887,0.690887,0.707203,0.676952,0.676952,0.676952,1.000000,1.000000,1.000000,1.000000
863,6,8-2,People used to live shorter lives because they...,People used to live shorter lives because they...,People used to live shorter lives because they...,In the past people did not have access to anti...,Chain,"Through history, most people didn't die of can...",0.814880,0.814880,0.814880,0.814880,0.683396,0.707203,0.707203,0.707203,1.000001,1.000001,1.000001,1.000001

## Between replicates

In [10]:
sim_ind = create_similarity_indep_replicates(results_jac, jaccard)
sim_ind.to_csv(f'{path_data_files}/data_processing/analysis_similarity_ind_jaccard.csv')
sim_ind.sort_values(by=["condition","k","layer_n"]).tail(30)

      condition  layer_n  k  story_merged
7390    Network        6  2      0.101695
7391    Network        6  2      0.066667
7392    Network        6  2      0.031746
7393    Network        6  2      0.116667
7394    Network        6  2      0.061224
7395    Network        6  2      0.092593
7396    Network        6  2      0.054054
7397    Network        6  2      0.028169
7398    Network        6  2      0.062500
7399    Network        6  2      0.120000
7400    Network        6  2      0.000000
7401    Network        6  2      0.090909
7402    Network        6  2      0.037037
7403    Network        6  2      0.062500
7404    Network        6  2      0.031250
7405    Network        6  2      0.105263
7406    Network        6  2      0.108108
7407    Network        6  2      0.000000
7408    Network        6  2      0.023256
7409    Network        6  2      0.031250
7410    Network        6  2      0.045455
7411    Network        6  2      0.033333
7412    Network        6  2      0.105263
7413    Network        6  2      0.039216
7414    Network        6  2      0.055556
7415    Network        6  2      0.038462
7416    Network        6  2      0.093750
7417    Network        6  2      0.045455
14106   Network        6  2      0.066667
14507   Network        6  2      0.102564

In [11]:
sim_ind = create_similarity_indep_replicates(results_trans, w2t)
sim_ind.to_csv(f'{path_data_files}/data_processing/analysis_similarity_ind_transformers.csv')
sim_ind.sort_values(by=["condition","k","layer_n"]).tail(30)

      condition  layer_n  k  story_merged
7390    Network        6  2      0.776695
7391    Network        6  2      0.494346
7392    Network        6  2      0.493790
7393    Network        6  2      0.580024
7394    Network        6  2      0.467075
7395    Network        6  2      0.601416
7396    Network        6  2      0.645517
7397    Network        6  2      0.583932
7398    Network        6  2      0.672692
7399    Network        6  2      0.734719
7400    Network        6  2      0.701330
7401    Network        6  2      0.674834
7402    Network        6  2      0.430068
7403    Network        6  2      0.761627
7404    Network        6  2      0.509031
7405    Network        6  2      0.599377
7406    Network        6  2      0.782087
7407    Network        6  2      0.593627
7408    Network        6  2      0.837258
7409    Network        6  2      0.683594
7410    Network        6  2      0.552357
7411    Network        6  2      0.700269
7412    Network        6  2      0.803985
7413    Network        6  2      0.728384
7414    Network        6  2      0.655112
7415    Network        6  2      0.583447
7416    Network        6  2      0.719445
7417    Network        6  2      0.626497
14106   Network        6  2      0.663714
14507   Network        6  2      0.615353